name: Deploy to Vultr

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VULTR_SSH_PRIVATE_KEY }}

    - name: Verify SSH connection
      run: ssh -o StrictHostKeyChecking=no root@${{ secrets.VULTR_IP }} "echo 'SSH connection successful'"

    # Add a step to install dependencies and build the project
    - name: Install dependencies and build project
      run: |
        npm install
        npm run build

    # Git clone instead of SCP
    - name: Deploy code to Vultr
      run: ssh -o StrictHostKeyChecking=no root@${{ secrets.VULTR_IP }} "cd /root/deploy/happiness-backend && git pull || git clone git@github.com:WAI-laboratory/happiness-backend.git /root/deploy/happiness-backend"

    - name: Restart Docker container
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.VULTR_IP }} "docker container stop happiness-backend || true"
        ssh -o StrictHostKeyChecking=no root@${{ secrets.VULTR_IP }} "docker container rm happiness-backend || true"
        ssh -o StrictHostKeyChecking=no root@${{ secrets.VULTR_IP }} "docker container run -d -p 80:3010 --name happiness-backend /root/deploy/happiness-backend"
